### ISSUE TITLE
Implement Differential Privacy for Prio3SumVec

### ISSUE THREAD

**Issue by bbirdsong2** [divviup/libprio-rs#1068]
We are currently using Prio3SumVec to submit reports to DAP and we are looking to introduce a small amount of noise to the results using differential privacy. We are flexible in how the noise is added, but as a starting point we think approximate/epsilon-delta DP, using I1-sensitivity, and the discrete Laplacian would be enough for our experiment.

Ideally this would be backwards compatible and we would not need to update our libprio-rs integration when submitting reports, and only need to pass in new parameters when calling the collector.

We are only looking to add a small amount of noise to the aggregated result counts  (i.e. +/- 1 or 2). Any implementation that provides this should suffice for our current use case.

**Comment by bbirdsong2** [comment]
Is it possible to get an estimated date on when this change will land? I noticed some discussion on the PR but I am not sure the current state of it or when it could be merged.

**Comment by divergentdave** [comment]
I think we should be able to get something out this week or next. It took me a bit to write up the proof justifying the mechanism, alongside working on other priorities. I'd like to give people a chance to review that, and resolve a couple other threads on DP specifics.

**Comment by cjpatton** [comment]
It's important that come to consensus on the details, as there is a good chance that we'll end up standardizing on whatever the outcome is. Let's take our time.
