### ISSUE TITLE
Add a method for is_valid to the Aggregator trait

### ISSUE THREAD

**Issue by divergentdave** [divviup/libprio-rs#1133]
We don't currently capture the `is_valid()` method defined in the VDAF spec in any traits. This is needed to safely use Poplar1, and Mastic (#1107) will need it as well.

**Comment by rozbb** [comment]
Some questions on this:

1. What precisely is the spec's [`is_valid()`](https://www.ietf.org/archive/id/draft-irtf-cfrg-vdaf-12.html#section-8.2.3) function doing with the list of previous agg params? It appears to only be reading 1 value from the list. Why is it a list?
2. How are aggregators expected to know the previous aggregation parameters for a given share? A dict of `input share => set(Poplar1AggregationParam)`?. How long are they supposed to retain this dict?

**Comment by divergentdave** [comment]
The interface is more expressive than strictly needed to allow for flexibility needed by future VDAFs. Mastic has the most interesting aggregation parameter validity conditions thus far: https://jimouris.github.io/draft-mouris-cfrg-mastic/draft-mouris-cfrg-mastic.html#name-validity-of-aggregation-par

This is connected to protections against replay attacks at the DAP level. The main strategy that implementations use to limit data storage needs is to define a time window of report timestamps that they will aggregate, and delete anti-replay data for reports that are old enough that they will no longer be accepted. For VDAFs with nontrivial aggregation parameters, the previously used aggregation parameters will be stored and deleted in the same way.

**Comment by divergentdave** [comment]
Fixed by #1139
