### ISSUE TITLE
Fields allowing representation of signed values

### ISSUE THREAD

**Issue by tgeoghegan** [divviup/libprio-rs#119]
In order to implement something like a [Prometheus gauge](https://prometheus.io/docs/concepts/metric_types/#gauge), we need to be able to measure negative values, represent them as `FieldElement`s and do all the usual secret sharing, validity proving and so on.

**Comment by tgeoghegan** [comment]
@cjpatton suggests using the existing fields, which represent unsigned values, but designating half the range to be negative. Then you would just need to "convert" signed values to their unsigned representation when running the input algorithm, and convert them back to unsigned after summing up the aggregate parts in the collector.

**Comment by divergentdave** [comment]
This has effectively been accomplished by the `FixedPointBoundedL2VecSum` type now. As discussed above, this is handled in the AFE's encoding and decoding functions, while operating over the same fields.
