### ISSUE TITLE
Optimization: Compare field elements by their Montgomery representation

### ISSUE THREAD

**Issue by divergentdave** [divviup/libprio-rs#208]
I noticed that the implementations of `PartialEq` and `Hash` for our fields convert from the internal representation, used for Montgomery multiplication, back to their p-residue form. We could save several multiplications per comparison if we used the Montgomery representation directly. Quoting from [the paper](https://www.ams.org/journals/mcom/1985-44-170/S0025-5718-1985-0777282-X/S0025-5718-1985-0777282-X.pdf), "Also unchanged are the algorithms for ... equality/inequality test". ~~It's possible we may need to perform the last conditional subtraction of p in `modp()`, as it appears that part of REDC has been broken out of `FieldParameters::mul()`.~~

**Comment by cjpatton** [comment]
Nice one! I'm a little out of my depth here. @armfazh wrote this code, so he may have an idea of whether this optimization is correct/safe.

**Comment by armfazh** [comment]
It's possible to make equality comparisons with numbers in Montgomery domain. 
OTOH changing the Hash method will break backwards compatibility, not sure if this is a  property that must be maintained.

**Comment by divergentdave** [comment]
The standard library docs say that `Hash` output of its types may change between compiler versions, and may differ across platforms. (see https://doc.rust-lang.org/std/hash/trait.Hash.html#portability) I think it would be acceptable if we changed hashing behavior of field elements, especially since we don't make any mention of it in the documentation.

**Comment by cjpatton** [comment]
I agree that's not a blocker. Can I ask a dumb question, though? Is it possible for a single field element to have multiple representations in the Montgomery domain?

**Comment by divergentdave** [comment]
The map to the Montgomery domain is equivalent to multiplying by R^-1 modulo p, where R is 2^128. This is straightforwardly bijective between the sets of residue classes, but we still have a choice of representatives for some residue classes, particularly p through u128::MAX. Thus, we either need to run values through `modp()`, or convince ourselves each possible source of a field element already does so.

**Comment by cjpatton** [comment]
SGTM. One thing to keep in mind is that, one day, we might end up replacing the field arithmetic with [fiat-crypto](https://github.com/mit-plv/fiat-crypto) so we're sure the implementation is correct. In the meantime.

**Comment by armfazh** [comment]
In the current implementation, one can go with the optimization suggested provided the elements are fully reduced in the range 0 to p-1. 
Also, if the field arithmetic becomes plug-able then it will be implementation-dependent how to implement the operators.
