### ISSUE TITLE
compiling libprio-rs to wasm fails to run

### ISSUE THREAD

**Issue by siyengar** [divviup/libprio-rs#209]
Compiling libprio to wasm fails to run. On further investigation it appears that the main reason for this is that there are symbols from ring's key agreement libraries that do not support the wasm target and explicitly disable it https://github.com/briansmith/ring/blob/155231fb017acaaa94a044f124bb34a777d115ef/src/lib.rs#L82

I experimented with a few solutions to this and it looks like one of the easiest solutions to this is to create a clone of the top level method that performs encryption of shares that does not perform encryption of shares. It might then be possible to use a pure js library to actually encrypt those shares in a format compatible with prio. Happy to put up a PR for this.

**Comment by cjpatton** [comment]
Innnteresting. I have been compiling to wasm for a bit now without much trouble, though I haven't tried to run the "Prio v2" stuff. Can you provide a bit more detail on your target and configuration? Is it failing to compile or failing at runtime?

**Comment by siyengar** [comment]
Have you tried initializing the wasm lib from js, or are you simply compiling? Wasm-pack will almost always succeed, but then error during initialization because there are unresolved symbols. 

Let me put up a quick repro rust project to show what I'm talking about. It's possible that you're using different top level methods than I am which could cause things to work for you. Wasm-pack is really good at eliding methods that are unused.

**Comment by divergentdave** [comment]
We dropped our dependency on ring a while ago, and #1059 made wasm-bindgen use cases a bit easier. Compiling an executable for the wasm32-wasip1 target succeeds, and it only has a small number of imports from "wasi_snapshot_preview1" so I'm confident there aren't any more symbol issues. I'm thus going to close this issue.
