### ISSUE TITLE
Consider implementing Prio2 as a VDAF

### ISSUE THREAD

**Issue by cjpatton** [divviup/libprio-rs#214]
Right now the v2 code is tightly integrated with ECIES encryption. However, it might be possible refactor the code so that Prio2 also implements the `Vdaf` API.  This may end up being useful for folks interesting in using a proof system that is currently more widely deployed.

The one wrinkle I see is that, in a VDAF, the query randomness would be generated by applying a PRF to a nonce. In the current v2 code, the query randomness is simply handed to each of the aggregators. What this means is that the v2 could couldn't be written in a way that uses the `Vdaf` API directly.

**Comment by cjpatton** [comment]
I've just opened https://github.com/divviup/libprio-rs/pull/240 for consideration. I realize this change is unlikely to land, but I would like to make two points about its merits:

1. Educational -- The distinction between Prio2 and Prio3 is often unclear. We often say that Prio3 is more general than Prio2, but this is slightly misleading:  While it's true that Prio3 solves the use case of Prio2 *and more*, the underlying proof system is incompatible. (A Prio3 client can't talk to a Prio2 aggregator.) If we land this change, we'd have something to point to.
2. Prio2 has already been widely deployed, but Prio3 has not. This might make someone more comfortable adopting Prio2 in the meantime.

**Comment by hanschen1996** [comment]
I agree with @cjpatton. It's not easy for someone who has deployed Prio2 to switch to Prio3, because e.g. Prio2 aggregator's input shares produced by a Prio2 client won't natively work for a Prio3 aggregator. Having a Prio2 VDAF will be better for those who have deployed Prio2 before and are still exploring the possibility of switching to Prio3.
