### ISSUE TITLE
Changes for vdaf-01

### ISSUE THREAD

**Issue by cjpatton** [divviup/libprio-rs#216]
Version 0.7.0 is locked to vdaf-00. Upgrading to vdaf-01 will require some changes, which this issue will track.

Because these changes will break compatibility with vdaf-00, it will be a good idea to cut a minor version before we start working on them (e.,g., move `x.y.z` yo `x.y.(z+1)`). Note that #210 should be solved before cutting the version.

Changes in the queue:
* 2022-05-13 https://github.com/cfrg/draft-irtf-cfrg-vdaf/pull/62 Drop public param and refactor verify parm
* 2022-05-17 https://github.com/cfrg/draft-irtf-cfrg-vdaf/pull/64 Breaking change to Prio3
* Update references to vdaf-01
* Update test vectors

**Comment by tgeoghegan** [comment]
I'd like to release a prio 0.7.1 that implements vdaf-00, and then we can start implementing vdaf-01 and eventually release prio 0.8.x from that.

Janus currently pins an unreleased commit of `libprio` in its `Cargo.toml` that is a few commits beyond `prio 0.7.0`. I've been holding off on releasing `prio 0.7.1` until we can be confident that the whole DAP interop branch can be implemented (we might still need to add some trait bounds to this-and-that).

So I think we should:

- finish Janus implementation of DAP/PPM interop branch + vdaf-00, taking whatever libprio-rs changes are needed along the way into `main`
- release prio 0.7.1, noting in the README that it implements vdaf-00
- start taking changes into libprio-rs `main` to support vdaf-01
- eventually release prio 0.8.0, noting in its README that it implements vdaf-01, and if you want vdaf-00, you should use prio 0.7

If you want to get started on vdaf-01 support in libprio-rs right away, then we could cut a `release/0.7` branch from `main` and continue to take vdaf-00 changes there, and then take on vdaf-01 changes on main.

>minor version before we start working on them (e.,g., move x.y.z yo x.y.(z+1))

n.b. in [SemVer](https://semver.org/) `z` is the _patch_ version.

**Comment by cjpatton** [comment]
Sounds like a plan to me, though it's not strictly necessary to make the change in 0.8.0. If an interm releasse is needed for some reason, we can do vdaf-01 in 0.9.0.

I don't think we're in a rush to get started on vdaf-01 support, especially since there are no breaking changes (yet).
