### ISSUE TITLE
vdaf: `Aggregator`: Handling prep-message shares and prep messages differently

### ISSUE THREAD

**Issue by cjpatton** [divviup/libprio-rs#220]
A "prep-message share" is emitted by each Aggregator during each round of the prep phase. These are preprocessed into a "prep message" using [`Vdaf.prep_shares_to_prep()`](https://cfrg.github.io/draft-irtf-cfrg-vdaf/draft-irtf-cfrg-vdaf.html#section-5).

https://github.com/cfrg/draft-irtf-cfrg-vdaf/pull/64 introduces a change to Prio3 that results in prep shares and prep messages having different contents. (In particular, this PR avoids including the proof verifier in the prep message, thereby saving on communication overhead.) In general there's no reason to think prep shares and prep messages need to have the same structure, it just so happens to be true for (the current versions of) our VDAFs.

In the VDAF syntax of the spec, this is not an issue because the caller is responsible for deserializing these inputs. However, this does present a problem for the current `Aggregator` API. I've been working on a port of Prio2 to VDAF (#214) that illustrates this problem: https://github.com/divviup/libprio-rs/compare/cjpatton/vdaf-first-round...cjpatton/prio2. Setting aside the merits of this idea, the code illustrates the crucial problem: Because the same struct is used for both (`Aggregator::PrepareMessage`), we need some way to distinguish one variant from the other. The same is true for the new version of Prio3.

Here are some remedies I've thought of:
1. Spec change: Have the encoding describe its variant, e.g., using a type byte. This is not desirable because we would like to keep the encoding as compact as possible.
2. Implementation change: Use the length of the raw bytes to distinguish between the variants. This is currently impossible given the way we've defined the `Decode`, which takes in a byte stream rather than a byte slice. (And rightfully so, I think.)
3. API change: Move serialization of prep shares and messages into `Aggregator` so that the API just takes in raw byte strings for each. This is not desirable because it's inconsistent with the rest of the API. Plus, in DAP the leader would end up unnecessarily deserializing its own prep share.
4. API change: Define a new associated type for `Aggregator`, call it `PrepareShare`. This seems like the only viable option to me.
5. Any other possibilities?

**Comment by divergentdave** [comment]
I would personally prefer defining a separate associated type. These two messages are different enough in purpose that I think they merit it. Using the same type for both reflects the influence of additive secret sharing, but VDAFs with different foundations will surely need this flexibility too. I've been thinking of them as the "broadcast message" and "reply messages" to keep things straight thus far.

**Comment by cjpatton** [comment]
I agree @divergentdave, though I'm open to other ideas.

I really like your idea of calling prep shares "broadcast messages". Why "reply message" for prep messages?

**Comment by divergentdave** [comment]
Ah, thinking about it more carefully "reply" is a misnomer, since the non-broadcast messages are the first ones to be sent in the protocol. It made more sense looking locally at the code path between the end of one aggregate request and the start of the next.

**Comment by cjpatton** [comment]
Taking a step back: prep share / prep message is terrible naming and I would love to replace this with something better. I wonder if we could find guidance on this in either the MPC or distributed systems literature.

**Comment by cjpatton** [comment]
I think both names should have the word "Prepare" in them. How about:
* prep share -> *PrepareBroadcast"
* prep message -> *PrepareMessage*, or maybe something else?
