### ISSUE TITLE
Best practice for affine (not linear) data encodings

### ISSUE THREAD

**Issue by MxmUrw** [divviup/libprio-rs#256]
While writing our fixed point, bound norm vector type, we had to deal with a difficulty caused by our choice of data encoding. To solve it, we needed to know the number of clients in the implementations of `decode_result()` and the number of aggregators in the implementation of `valid()`. In the following I will explain in some more detail why we need that information.

### Our data encoding
We deal with fixed point numbers, mostly in the range `[-1,1]`.
To represent them in prio, we use the range `[0,2^n)`. To calculate the "semantic value" of a number $y$ encoded in the prio range, we do the obvious thing: rescale to `[0,2]` and shift by 1, namely: 
$$V(y) = \frac{y}{2^{n-1}} -1$$

### Problem 1: decoding
The (now relevant part of our) use-case is that each client submits a fixed point number. We are interested in the sum of those numbers. The problem is that the sum that is automatically computed by prio during accumulation is done in "the prio range" `[0,2^n)`: It turns out that we cannot simply use the decoding function `V`, because it is not linear. What we have to do, e.g. for the case of 2 clients, is:
$$V(y) + V(z) \quad = \quad \frac{y + z}{2^{n-1}} - 2$$
And in the general case we have to subtract the number of clients instead of the `2`.

### Problem 2: validation circuit
A similar effect is seen in the circuit: Our calculation has a non-linear part (a constant summand that is required because of the "shift by 1" in the prio range). This works, as long as the circuit is evaluated locally by the client. In a distributed evaluation by the aggregators, that constant summand appears too often in the calculation: once for every aggregator. So what we do here, is to first multiply the constant by `1/num_of_aggregators` in the circuit.

Alternatively, we could also make this work by including a "constant 1 field element" in the shares. As that 1 is distributed among the aggregators, we multiply the constant summand with a share of that 1.

### Conclusion
We currently provide this information manually when constructing our prio type, and store it in the struct. Is that how this situation should be handled?

If some more details are required (for example about the validation circuit, etc.), I will gladly provide more.

**Comment by divergentdave** [comment]
I think the decoding problem suggests we should provide the number of reports to `Vdaf.agg_shares_to_result` (here, `Type::decode_result()` and `Vdaf::unshard()`.

To solve the validation problem, I recommend following the example of the histogram implementation, which does what you currently do. Its validity circuit has an affine part, and it has each aggregator add $-1*num\\_shares^{-1}$ in its calculation of this. This `num_shares` is provided to the validity method already, so it is not necessary to store it from a constructor.

**Comment by MxmUrw** [comment]
Thanks for pointing out that the `num_shares` information is already available - I missed that, because I mistakenly used the number of clients in both cases, and only noticed that we actually need two different numbers while writing the issue description.

About the decoding problem: Yep, having that info would be nice.

**Comment by MxmUrw** [comment]
Sure!

It seems that there are 3 things to be done: Changing the draft, the python reference implementation, and this rust implementation. Is that correct? I don't think I should be writing the draft, as @divergentdave is going to know better what exactly needs to be changed. But I could definitely work on the code changes that fall out from that.

**Comment by cjpatton** [comment]
I think just adding the change to libprio is a reasonable first step. In many cases we have been prototyping new features/algorithms in libprio before moving them to the spec. The main reason is that this gives us a chance to figure out if the change is actually feasible/useful and therefore worth being in the VDAF draft. This means that libprio might have a different feature set than what's in the draft at any given time. I think this is OK, we just want to make sure there are no regressions. (We have test vectors to make sure we don't break interop with the spec.)

Note that this repo's maintainers (@tgeoghegan et al) may decide to re-consider this policy in the future.

**Comment by cjpatton** [comment]
Closing as solved by #258.
