### ISSUE TITLE
Emit Prometheus/OpenMetrics performance metrics

### ISSUE THREAD

**Issue by tgeoghegan** [divviup/libprio-rs#26]
`libprio-rs` has been deployed in the ENPA `prio-server` for some time now. As we work on adapting it for future metrics projects, we will want to revisit questions like the protocol for encoding and transmitting input shares from clients to aggregators. For instance, my suspicion is that we spend a lot of time doing ECDH to derive the per-packet symmetric encryption key, and in future revisions, we might want to use a single symmetric key for many packets, or perhaps use an HMAC construction to derive unique keys from a master key derived via ECDH. In any case, before we can debate such questions, we should take measurements! This issue is about adding profiling code to `libprio-rs` so that `prio-server` can then emit metrics to Prometheus about performance.

**Comment by cjpatton** [comment]
> For instance, my suspicion is that we spend a lot of time doing ECDH to derive the per-packet symmetric encryption key, and in future revisions, we might want to use a single symmetric key for many packets, or perhaps use an HMAC construction to derive unique keys from a master key derived via ECDH.

For what it's worth, [HPKE](https://www.ietf.org/archive/id/draft-irtf-cfrg-hpke-08.html) provides an API that supports all of these use cases. For Prio v3, I think we should move away from ECIES and use HPKE instead. 


> In any case, before we can debate such questions, we should take measurements! This issue is about adding profiling code to `libprio-rs` so that `prio-server` can then emit metrics to Prometheus about performance.

Some initial thoughts on things we should benchmark.
1. `add`, `mul`, and `inv` for each implementation of FieldElement.
2. FFT operations (already exists).
3. Proof generation and verification time for each data type (`prove` and `query` respectively; see #23).
4. Proof generation and verification time, including encryption and decryption of the share, for each data type.

The delta between (3) and (4) let's us get a sense of how much the public key crypto costs compared to the zero-knowledge proof stuff. Note that for (4) we still need to work out the details of secret-sharing / encryption for Prio v3.

**Comment by cjpatton** [comment]
FWIW, dalek-cryptography's implementation of X25519 takes about 52 microseconds:
```
     Running /home/chris/github.com/dalek-cryptography/x25519-dalek/target/release/deps/x25519-85f4b58864dbbb9b
WARNING: HTML report generation will become a non-default optional feature in Criterion.rs 0.4.0.
This feature is being moved to cargo-criterion (https://github.com/bheisler/cargo-criterion) and will be optional in a future version of Criterion.rs. To silence this warning, either switch to cargo-criterion or enable the 'html_reports' feature in your Cargo.toml.

Gnuplot not found, using plotters backend
diffie_hellman          time:   [52.245 us 52.597 us 52.995 us]                           
Found 2 outliers among 100 measurements (2.00%)
  1 (1.00%) high mild
  1 (1.00%) high severe
```

That's roughly the runtime of generating a proof for a length-100 boolean vector (see #30). There's room to optimize our code a bit, but basically we should expect the cost of proof generation to outweigh the cost of encryption for large enough inputs.

**Comment by rsk97** [comment]
Will the current implementation be able to scale to millions of devices (clients), if I want to share 0/1 from each client and have 2 servers?

If not, what do you see as the bottleneck in this implementation.

**Comment by cjpatton** [comment]
@tgeoghegan can comment on the scalability of current deployments.

**Comment by tgeoghegan** [comment]
The deployment in support of ENPA (abetterinternet/prio-server) does currently support millions of iOS and Android devices, though aggregations remain a bottleneck in the current implementation.

**Comment by rsk97** [comment]
That's great! @tgeoghegan - are there some instructions/documentation on how to simulate the server (with predefined inputs) without using any cloud service (AWS/GCP)?

**Comment by tgeoghegan** [comment]
Yes, you can drive `prio-server`'s `facilitator` component at the command line to generate sample data shares, generate verification messages over them and then aggregate as discussed in [this README](https://github.com/abetterinternet/prio-server/blob/main/facilitator/README.md). @rsk97 if you have more questions about that, could I ask you to open an issue on [prio-server](https://github.com/abetterinternet/prio-server/issues)? I'd like to keep this issue focused on the question of adding performance metrics to `libprio-rs`.

**Comment by cjpatton** [comment]
Anything else we want to add? We have prio3 benchmarks for the client, it may be worth adding benchmarks for the aggregator.

**Comment by tgeoghegan** [comment]
This issue is about computing performance metrics and optionally exposing them in Prometheus or OpenMetrics metrics scrapes using the [official client](https://github.com/prometheus/client_rust).

**Comment by cjpatton** [comment]
It seems like it would b better to add these hooks in the code that calls libprio.

**Comment by divergentdave** [comment]
I'm going to close this, as there doesn't seem to be much need for observability integration directly with this crate. It is straightforward for consumers to record the time that VDAF operations take, and we currently do so using OpenTelemetry trace spans over in Janus.
