### ISSUE TITLE
Decouple `Vdaf::Measurement` and `Vdaf::AggregateResult` from `FieldElement::Integer`

### ISSUE THREAD

**Issue by tgeoghegan** [divviup/libprio-rs#302]
In `Prio3Aes128Count`, measurements must be in `[0, 2)`. However, the way we have wired up the implementation of trait `Vdaf` on `Prio3` with the underlying `Type`s from `flp::types` means that you end up with a method `Prio3Aes128Count::shard(&self, &u64)`, because `Prio3Aes128Count` uses `Field64`, and `Field64::Integer` is `u64`.

The size of the prime field used by a VDAF seems like an implementation detail that the caller shouldn't need to care about. We ought to be able to re-arrange these associated types so that `Prio3Aes128Count::Measurement` is decoupled from the field and its integer type.

**Comment by divergentdave** [comment]
These types are uncoupled now, generally speaking. (Note that `Prio3Histogram::Measurement` is `usize`.) #897 finishes this by changing the `Prio3Count` measurement type to `bool`.
