### ISSUE TITLE
Change codepoints of non-standardized VDAFs

### ISSUE THREAD

**Issue by divergentdave** [divviup/libprio-rs#306]
Split out from https://github.com/divviup/libprio-rs/pull/283#discussion_r967569523: We should change the `ID` of `Average`, `CountVec`, `Prio2`, and `Poplar`. Currently they all use `0xFFFF0000`. This will be a proof-breaking change. We should also add a unit test that asserts that these are all distinct. (That test will have to be updated by hand as we add new VDAFs)

**Comment by divergentdave** [comment]
How about we write a centralized registry of all the private use algorithm IDs we use as part of the doc comment for `prio::vdaf::Vdaf::ID`? That would be useful for reference purposes, and we could add comments pointing between that documentation and the distinct codepoint unit test.

**Comment by divergentdave** [comment]
The goal of using distinct codepoints is to provide domain separation between "challenge" randomness used in different VDAFs, which greatly simplifies security analysis by ruling out cross-protocol attacks between different VDAFs.

One alternate approach we could take is to push down selecting an identifier from the private use range to libprio-rs users, and requiring that an identifier be passed to the relevant constructors. Perhaps that is going too far?

**Comment by cjpatton** [comment]
> The goal of using distinct codepoints is to provide domain separation between "challenge" randomness used in different VDAFs, which greatly simplifies security analysis by ruling out cross-protocol attacks between different VDAFs.

I agree -- this is the security-conservative thing to do. 


> One alternate approach we could take is to push down selecting an identifier from the private use range to libprio-rs users, and requiring that an identifier be passed to the relevant constructors. Perhaps that is going too far?

This is going a bit too far.

All I think that's needed right now is a unit test that checks that all of the `Vdaf` implementers in our crate have distinct IDs.

**Comment by cjpatton** [comment]
Fair enough. I'm happy either way, though we should probably get on adding CountVec to the draft since it looks like y'all plan to use it soon?

**Comment by divergentdave** [comment]
After some further discussion, we've decided to leave these as-is. The following considerations support this approach:

- Theoretical attacks arising from reuse of algorithm identifiers could only affect robustness, not privacy.
- We would like to get Prio3Aes128CountVec written up and standardized soon in the near/medium term, at which point it will have its own non-private identifier.
- The Prio2 VDAF does not incorporate its own algorithm identifier into any calculations, so it would not be affected either way.
