### ISSUE TITLE
Eliminate `mod util`

### ISSUE THREAD

**Issue by tgeoghegan** [divviup/libprio-rs#32]
Utility modules are a code smell (citation needed) so we should aim to get rid of `libprio-rs`' `mod util`. If anything in there is useful it should be refactored into more appropriate and meaningful modules, and there are likely opportunities to trim the crate's public API surface of interfaces that aren't quite useful enough to justify being exported.

**Comment by cjpatton** [comment]
All that's left here is serializing/deserializing Prio2 proofs. Perhaps we could fold this code into `vdaf::prio2`? Would it get you all into trouble if the error types change?

**Comment by tgeoghegan** [comment]
I don't think there's any better place for this stuff at the moment, except maybe `lib.rs`. At most I think we could make everything in there `pub(crate)` instead of `pub`, but let's wait and see what happens with ENPA before we make a decision here.

**Comment by divergentdave** [comment]
Done in #660.
