### ISSUE TITLE
Replace `L` with `SEED_SIZE`

### ISSUE THREAD

**Issue by cjpatton** [divviup/libprio-rs#464]
_Originally posted by @cjpatton in https://github.com/divviup/libprio-rs/pull/455#discussion_r1113517082_

**Comment by cjpatton** [comment]
@tgeoghegan can we schedule this for VDAF-04? I'm happy to take it.

**Comment by tgeoghegan** [comment]
Yeah, we'll have to bump the crate minor version for VDAF-04 anyway, so we can certainly rename the const generic.

**Comment by divergentdave** [comment]
FWIW, I don't think renaming the parameter from `L` to `SEED_SIZE` is a breaking change, as generic parameters are only identified by the order in which they appear in angle brackets. In fact, the parameter name in the trait definition does not need to match any other parameters. (though of course they should match, for readability) Each `impl` block declares its own type variables, which are lexically scoped to that `impl` block, and then slots those variables into generic type parameters of types and traits.
