### ISSUE TITLE
Deserialization of Poplar1 prepare message

### ISSUE THREAD

**Issue by divergentdave** [divviup/libprio-rs#467]
The `Aggregator` trait currently says that its `PrepareShare` and `PrepareMessage` associated types must both implement `ParameterizedDecode<Self::PrepareState>`. This poses a problem because, in VDAF-03 and VDAF-04, the encoded length of a Poplar1 prepare message cannot be determined a priori from the prepare state. `prep_shares_to_prep()` will send a zero-length string in lieu of an encoded zero vector. (this happens on the second round of sketching during a successful preparation, and saves broadcasting one field element) If it weren't for this optimization, the length could be determined from the prepare state, since it tells us which field to use, and the current sketching round.

In practice, in the context of DAP, the prepare message is sent alone in a TLS-style length delimited field. It would be technically possible for the `ParameterizedDecode` implementation to peek at the `Cursor`'s remaining length, but that would go against the typical API contract of this trait, and break its composability.

We could solve this by introducing a new trait to greedily deserialize an entire byte slice with an additional parameter. If the VDAF spec dropped this optimization, then `ParameterizedDecode` would be a better fit.

**Comment by cjpatton** [comment]
Oooofta.

There a couple other similar situations to consider:
* Prio2: the prep message is always ''
* Prio3: the prep message is '' if no joint randomness is used

In all of these situations, you expect an empty string as the prep message; a non-empty prep message should fail to parse. Since our decoder ignores the rest of the buffer, it is therefore up to the caller to ensure the buffer is exhausted. Is that the problem?

**Comment by divergentdave** [comment]
Ah, we could also solve this problem by making the opposite optimization in the VDAF spec, and hoisting the decision into `prep_shares_to_prep()`. If we check for zero in there after sketch round two, and always output the empty string or an error, that gives us the same communication savings and predictable message lengths.

The provided `get_encoded()`/`get_encoded_with_param()` methods do check that all input was consumed after decoding. The problem is more that the decode methods have been, up to now, EOF-agnostic.

**Comment by cjpatton** [comment]
Putting aside the optimization (which I think is good), I still don't think I'm quite getting the problem.

**Comment by divergentdave** [comment]
This distinction came up in #382, but with a different struct. We used to use `TryFrom<&'a [u8]>` for deserialization of some types, and `Decode` for others. I called the former "greedy deserialization", because they always consumed the entirety of the slice they were passed. `Decode` and the like reads exactly what it needs to from a cursor, advances the cursor's position, and does not look at the amount of data left in the cursor. (at least, so far) In the event that we have another deserialization routine that cares about how much input is left, I think it should live under a different trait, since it effectively has a different API contract, and doesn't compose in the same way.

In practice, this would only come up on the round 2 prepare message in Poplar. If sketch verification fails, the last prepare message would have been one field element long. If sketch verification succeeds, the last prepare message would have been empty, due to the existing optimization.

**Comment by cjpatton** [comment]
> .. in the vent that we have another deserialization routine that cares about how much input is left ...

The current decode traits are built around DAP messages, which are designed to allow us to decode without knowing the length of the rest buffer; it is the caller's responsibility to make sure the buffer is exhausted after decoding.

Is the same not true for VDAF messages? Suppose I "decode" an empty string, and verification "succeeds" despite the fact that there are still bytes left in the buffer (i.e., the prep message is malformed, so verification should fail.) Doesn't the API contract still require the caller to check that the buffer is empty (and fail if not)?

Is there something else going on here that I'm missing?

Of course, we could improve security of implementations if we had an API that made this check unnecessary. Can we do so in a general way?

Regardless, I like the suggested change to the spec, as it provides defense-in-depth for implementations.

**Comment by divergentdave** [comment]
Fixed in #501. (and cfrg/draft-irtf-cfrg-vdaf#174)
