### ISSUE TITLE
ParameterizedEncode could be removed

### ISSUE THREAD

**Issue by divergentdave** [divviup/libprio-rs#478]
I noticed that we have a `ParameterizedEncode` trait that is largely unused, except for via blanket implementations on `Encode` types. As far as I'm aware, everything that needs to go on the wire already contains all the information needed to encode itself. We could remove this to simplify the API.

**Comment by cjpatton** [comment]
Daphne uses `ParameterizedEncode` for DAP-version dependent messages: https://github.com/cloudflare/daphne/blob/main/daphne/src/messages/mod.rs#L179
