### ISSUE TITLE
Consolidate crypto dependencies by adopting ring for AES GCM

### ISSUE THREAD

**Issue by tgeoghegan** [divviup/libprio-rs#52]
We currently pull in [aes](https://crates.io/crates/aes) for AES-GCM (used to encrypt/decrypt data shares) and AES-CTR (used in the PRNG). We already use [ring](https://crates.io/crates/aes) for ECDH (and for many other things in `prio-serve`), so we could use `ring::aead` for GCM.

**Comment by cjpatton** [comment]
This issue seems pretty stale. Now that the prio-server dependencies are behind a flag, is there anything else we need to do here?
