### ISSUE TITLE
Prio2: VDAF preparation may evaluate polynomial at a root of unity

### ISSUE THREAD

**Issue by divergentdave** [divviup/libprio-rs#658]
I was working on removing parts of the unused ENPA API, and I noticed that the VDAF version of Prio2 is missing a rejection sampling loop when choosing its evaluation point.

https://github.com/divviup/libprio-rs/blob/e51270cfd3a5ce65dd8e3d7ccec79cdd16e08515/src/server.rs#L148-L162

https://github.com/divviup/libprio-rs/blob/e51270cfd3a5ce65dd8e3d7ccec79cdd16e08515/src/vdaf/prio2.rs#L221-L223

This means it may choose a root of unity as an evaluation point, which leaks one digit of the input to the aggregators, breaking the zero knowledge property. The probability of this happening is approximately equal to the input's dimension over 2<sup>32</sup>. We should make a breaking change to fix this by adding the same rejection sampling loop to `prepare_init()`.

cc @cjpatton

**Comment by tgeoghegan** [comment]
> We should make a breaking change to fix this

We have yet to release `prio` 0.14.0 with #650, which is a breaking change anyway, so we have a great opportunity to fix this.
