### ISSUE TITLE
Investigate performance benefit of pre-computing roots of unity

### ISSUE THREAD

**Issue by cjpatton** [divviup/libprio-rs#707]
The only parts of `multi_discrete_fourier_transform()` that get reused are index math and taking powers of the first root of unity. The vast majority of the field element arithmetic still has to be done separately for each input polynomial. I ran cachegrind on the prio3_client_count_vec_1000 benchmark, before and after this change, and processed the results with `cg_diff` and `cg_annotate`. The total number of instructions in `multi_discrete_fourier_transform()` exceeds the number of instructions in `discrete_fourier_transform()`, by 9.6e6 to 7.0e6. Data reads and writes are up by similar ratios, and data first-layer cache misses jumped by an order of magnitude, 1,555 to 24,005. Based on this, I think the changes to support interleaving multiple input polynomials must have negatively affected compiler optimizations enough to outweigh the computations that it was able to reuse. Plus, interleaving processing of multiple polynomials increases the working set size, and hurts cache locality.

There is an alternate optimization we could make to `discrete_fourier_transform()`: currently we load a root of unity in an outermost loop, and exponentiate it in a nested loop. We have already precomputed all the roots of unity, so we could instead do some power-of-two modular arithmetic and look up all powers of the root from the precomputed table. (we would want `F::root((l * i) % num_roots)`) If we were to make that change, then all field arithmetic in the function would be input-dependent.

Based on the above, I don't think the `multi_discrete_fourier_transform()` change will pay off.

_Originally posted by @divergentdave in https://github.com/divviup/libprio-rs/pull/668#discussion_r1305925571_

**Comment by cjpatton** [comment]
Hmm @divergentdave didn't we discuss this and decide it's a dead end?

**Comment by divergentdave** [comment]
I think we ended up on the idea that it might make sense if we cap the size of the table. Between the extra complexity, and the low potential payoff (just one multiplication per loop in a multiplication-heavy procedure), I'm okay with abandoning this idea.
