### ISSUE TITLE
Instrument with tokio-rs/tracing

### ISSUE THREAD

**Issue by tgeoghegan** [divviup/libprio-rs#72]
[`tracing`](https://github.com/tokio-rs/tracing) allows lightweight tracing of events in Rust programs. We should use `tracing` in `libprio-rs` so that clients can opt into it by configuring a `tracing-subscriber`.

**Comment by cjpatton** [comment]
Is this still needed/desirable? I have a bit more experience with tracing now, and I'm a bit concerned that it would be too computationally intensive to have too much tracing in the low level crypto code.

**Comment by tgeoghegan** [comment]
We may encounter performance problems in the future that we investigate by adding traces to `libprio-rs`, but in the meantime, this issue doesn't really capture any useful information, so I think we can close it.
