### ISSUE TITLE
Eliminate prio2 Cargo feature

### ISSUE THREAD

**Issue by divergentdave** [divviup/libprio-rs#902]
Following #901, `prio2` and `crypto-dependencies` will turn on the same set of optional dependencies. I think we should eliminate this feature, and gate the Prio2 VDAF either behind `#[cfg(feature = "crypto-dependencies)]` or `#[cfg(all(feature = "crypto-dependencies", feature = "experimental"))]`. We should do this before cutting 0.16.0.

**Comment by cjpatton** [comment]
The latter feature set sounds better to me.
